package local.redes;

import java.io.DataInputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;

/**
 *
 * @author Pedro Cristovão Lopes Fogaça
 */
public class FormCliente extends javax.swing.JFrame {

    private static Socket conexao;
    private static ObjectOutputStream saida; 
    private static DataInputStream entrada; 
    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jeditNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jeditIdade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtextareaLog = new javax.swing.JTextArea();
        jbtnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jtfmCliente"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Nome");
        jLabel1.setName("jlblNomeCliente"); // NOI18N

        jeditNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jeditNome.setName("jtxtNomeCliente"); // NOI18N

        jLabel2.setText("Idade");
        jLabel2.setName("jlblIdade"); // NOI18N

        jeditIdade.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jeditIdade.setName("jtxtIdade"); // NOI18N

        jLabel3.setText("Retorno do Servidor");
        jLabel3.setName("jlblRetornoServidor"); // NOI18N

        jtextareaLog.setEditable(false);
        jtextareaLog.setColumns(20);
        jtextareaLog.setRows(5);
        jtextareaLog.setName("jtxtareaLog"); // NOI18N
        jScrollPane1.setViewportView(jtextareaLog);

        jbtnEnviar.setText("Enviar");
        jbtnEnviar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEnviar.setName("jbtnEnviar"); // NOI18N
        jbtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(jeditNome)
                    .addComponent(jeditIdade)
                    .addComponent(jbtnEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jeditNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jeditIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbtnEnviar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnviarActionPerformed
         enviarDadosAoServidor();
    }//GEN-LAST:event_jbtnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    public void enviarDadosAoServidor() {
        try {
            conexao = new Socket("127.0.0.1", 50000);
            
            Pessoa pessoa = new Pessoa();
            pessoa.setNome(jeditNome.getText());
            pessoa.setIdade(Integer.parseInt(jeditIdade.getText()));
            
            saida = new ObjectOutputStream(conexao.getOutputStream());
            saida.writeObject(pessoa);
           
            entrada = new DataInputStream(conexao.getInputStream());
            String resposta = entrada.readUTF();
            
            jtextareaLog.append("Recebeu do Servidor: \n");
            jtextareaLog.append(resposta + "\n");
       
            saida.close();
            entrada.close();
            conexao.close();    
        } catch(IOException ex) {
            jtextareaLog.append("Erro: " + ex.getMessage() + "\n");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnEnviar;
    private javax.swing.JTextField jeditIdade;
    private javax.swing.JTextField jeditNome;
    private javax.swing.JTextArea jtextareaLog;
    // End of variables declaration//GEN-END:variables
}
