package local.redes;

import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Cristovão Lopes Fogaça
 */
public class frmCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmCliente.class.getName());

    private Cliente cliente;
    /**
     * Creates new form frmCliente
     */
    public frmCliente() {
        initComponents();
        setLocationRelativeTo(null);
        
        try {
             cliente = new Cliente();
        } catch (MalformedURLException ex) {          
            JOptionPane.showMessageDialog(this, "Erro: " +
                      "ao conectar no servidor: " + ex.getMessage(),
                    "Erro", JOptionPane.WARNING_MESSAGE); 
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " +
                      "retornado pelo servidor: " + ex.getMessage(),
                    "Erro", JOptionPane.WARNING_MESSAGE);
        } catch (NotBoundException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(),
                    "Erro", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(),
                    "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPartido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeCandidato = new javax.swing.JTextField();
        btnGravarCadastro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbbCanditatos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtQtdVotos = new javax.swing.JTextField();
        btnEnviarVotosAoServidorCentral = new javax.swing.JButton();
        txtRetorno = new javax.swing.JTextField();
        btnEncerrarUrna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Urna Eletrônica");
        setName("frmCliente"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Urna Java");
        jLabel1.setName("lblCabecalho"); // NOI18N

        jLabel2.setLabelFor(txtPartido);
        jLabel2.setText("Codigo Partido");

        txtPartido.setName("txtPartido"); // NOI18N

        jLabel3.setLabelFor(txtNomeCandidato);
        jLabel3.setText("Nome Candidato");
        jLabel3.setName("lblNomeCandidato"); // NOI18N

        btnGravarCadastro.setText("Gravar Cadastro");
        btnGravarCadastro.setActionCommand("btnEnvirCadastro");
        btnGravarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarCadastroActionPerformed(evt);
            }
        });

        jLabel4.setText("Selecione o Candidato");
        jLabel4.setName("lblSelecionarCandidato"); // NOI18N

        cbbCanditatos.setName("cbbCandidatos"); // NOI18N
        cbbCanditatos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbbCanditatosFocusGained(evt);
            }
        });
        cbbCanditatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbbCanditatosKeyPressed(evt);
            }
        });

        jLabel5.setText("Quantidade De Votos");
        jLabel5.setName("lblQtdVotos"); // NOI18N

        txtQtdVotos.setName("txtQtdVotos"); // NOI18N

        btnEnviarVotosAoServidorCentral.setText("Enviar ao Servidor Central");
        btnEnviarVotosAoServidorCentral.setName("btnENviarVotos"); // NOI18N
        btnEnviarVotosAoServidorCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarVotosAoServidorCentralActionPerformed(evt);
            }
        });

        txtRetorno.setEnabled(false);
        txtRetorno.setName("txtRetorno"); // NOI18N

        btnEncerrarUrna.setText("Encerrar Urna");
        btnEncerrarUrna.setName("btnEncerrarUrna"); // NOI18N
        btnEncerrarUrna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrarUrnaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGravarCadastro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtQtdVotos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbbCanditatos, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnviarVotosAoServidorCentral)
                            .addComponent(txtRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEncerrarUrna, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addComponent(btnGravarCadastro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbCanditatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtQtdVotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnEnviarVotosAoServidorCentral)
                .addGap(18, 18, 18)
                .addComponent(txtRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEncerrarUrna)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        btnEncerrarUrna.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarCadastroActionPerformed
        if (txtPartido.getText().trim().isEmpty()) {            
            JOptionPane.showMessageDialog(this, "Preencha o numero do partido!",
                    "Campo vazio", JOptionPane.WARNING_MESSAGE);
            txtPartido.requestFocus();
            return;
        }
        
        if (txtNomeCandidato.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o nome do(a) candidato(a)!",
                    "Campo vazio", JOptionPane.WARNING_MESSAGE);
            txtNomeCandidato.requestFocus();
            return;
        }
      
        try {
            String nome = txtNomeCandidato.getText();
            int numPartido = Integer.parseInt(txtPartido.getText());

            Candidato candidato = new Candidato();
            candidato.setNome(nome);
            candidato.setNumeroDoPartido(numPartido);
            cliente.cadastrarCandidato(candidato);
            
            txtNomeCandidato.setText("");
            txtPartido.setText("");
            txtPartido.requestFocus();
            
            atualizaComboCandidatos();   
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", 
                    JOptionPane.WARNING_MESSAGE);
        } catch (CandidatoExisteException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Atenção", 
                    JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar! "
                            + ex.getMessage(), "Erro", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarCadastroActionPerformed

    private void btnEnviarVotosAoServidorCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarVotosAoServidorCentralActionPerformed
        int numeroPartido = 0;
        int qtdVotosCandidatoSelecionado = 0;
        
        if (txtQtdVotos.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a quantidade de votos" 
                        , "Campo vazio", JOptionPane.WARNING_MESSAGE);
            txtQtdVotos.requestFocus();
            return;
        }
                
        Candidato candidatoSelecionado = (Candidato)cbbCanditatos.getSelectedItem();
        
        int resposta = JOptionPane.showConfirmDialog(
                null, 
                "Registrar votos para o(a) candidato(a) " +candidatoSelecionado.toString() +"?",
                "Registros de Votos",
                JOptionPane.YES_NO_OPTION                     
        );
        
        if (resposta == JOptionPane.NO_OPTION) {
            return;
        }
        
        if (candidatoSelecionado != null) {
            
            try {
                numeroPartido = candidatoSelecionado.getNumeroDoPartido();
                qtdVotosCandidatoSelecionado = Integer.parseInt(txtQtdVotos.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Digite número válido!", "Erro", 
                         JOptionPane.WARNING_MESSAGE);  
            }
            
            if (qtdVotosCandidatoSelecionado < 1) {
                JOptionPane.showMessageDialog(this, "Quatidade de votos deve ser maior que zero!", 
                        "Erro", JOptionPane.WARNING_MESSAGE);  
            }
            
            try {
                cliente.registrarVotos(numeroPartido, qtdVotosCandidatoSelecionado);
                
                txtRetorno.setText("Votos do(a) candidato(a) "+candidatoSelecionado.toString()
                        + " enviados com sucesso!");
                
                txtQtdVotos.setText(""); 
            } catch (RemoteException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao Registrar Votos! " 
                         + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao Registrar Votos! " 
                         + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEnviarVotosAoServidorCentralActionPerformed

    private void cbbCanditatosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbbCanditatosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbCanditatosKeyPressed

    private void cbbCanditatosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbbCanditatosFocusGained
        atualizaComboCandidatos();
    }//GEN-LAST:event_cbbCanditatosFocusGained

    private void btnEncerrarUrnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrarUrnaActionPerformed
        
        int resposta = JOptionPane.showConfirmDialog(
                null, 
                "Confirma Encerramento da urna?",
                "Encerrar Urna",
                JOptionPane.YES_NO_OPTION                     
        );
        
        if (resposta == JOptionPane.YES_OPTION) {
            cliente.desconectar();
            txtPartido.setEnabled(false);
            txtNomeCandidato.setEnabled(false);
            cbbCanditatos.setEnabled(false);
            txtQtdVotos.setEnabled(false);
            btnGravarCadastro.setEnabled(false);
            btnEnviarVotosAoServidorCentral.setEnabled(false);
            btnEncerrarUrna.setEnabled(false);
            txtRetorno.setText("Sessão encerrada!");
        }
    }//GEN-LAST:event_btnEncerrarUrnaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmCliente().setVisible(true));
    }
    
    public void atualizaComboCandidatos() {
        try {
            cbbCanditatos.removeAllItems();
            
            List<Candidato> lista = cliente.obterListaDeCandidatos();

            for (Candidato c : lista) {
                cbbCanditatos.addItem(c);
            }
           
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Erro listar candidatos! " 
                    + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);   
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao listar candidatos! "
                    + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncerrarUrna;
    private javax.swing.JButton btnEnviarVotosAoServidorCentral;
    private javax.swing.JButton btnGravarCadastro;
    private javax.swing.JComboBox<Candidato> cbbCanditatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtNomeCandidato;
    private javax.swing.JTextField txtPartido;
    private javax.swing.JTextField txtQtdVotos;
    private javax.swing.JTextField txtRetorno;
    // End of variables declaration//GEN-END:variables
}
