/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaCliente.java
 */
package manipula_texto;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author fabricio@utfpr.edu.br
 */
public class JanelaCliente extends javax.swing.JFrame {

    private ListaDeClientes listaDeClientes = null;
    private ManipulaTexto mt = null;
    private int posicaoAtual = 0;
    private boolean alterar = false;

    /** Creates new form JanelaCliente */
    public JanelaCliente() {
        initComponents();
        listaDeClientes = new ListaDeClientes();
        mt = new ManipulaTexto(); 
        controlaBotoesECampos(false, false, false, false, false);   
    }
    
    public void controlaBotoesECampos(boolean novo, boolean gravar, boolean editar, boolean excluir, boolean campos){
        jBtnNovo.setEnabled(novo);
        jBtnGravar.setEnabled(gravar);
        jBtnEditar.setEnabled(editar);
        jBtnRemover.setEnabled(excluir);
        jTFNome.setEnabled(campos);
        jTFFone.setEnabled(campos);
        jSIdade.setEnabled(campos);
        if (campos){
            jTFNome.requestFocus();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnNovo = new javax.swing.JButton();
        jBtnFechar = new javax.swing.JButton();
        jTFNome = new javax.swing.JTextField();
        jTFFone = new javax.swing.JTextField();
        jSIdade = new javax.swing.JSpinner();
        jBtnGravar = new javax.swing.JButton();
        jBtnProximo = new javax.swing.JButton();
        jBtnAnterior = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnRemover = new javax.swing.JButton();
        jBtnAbrirArquivo = new javax.swing.JButton();
        jBtnNovoArquivo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTFPosicaoAtual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Fone:");

        jLabel3.setText("Idade:");

        jBtnNovo.setText("Novo");
        jBtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoActionPerformed(evt);
            }
        });

        jBtnFechar.setText("Fechar");
        jBtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFecharActionPerformed(evt);
            }
        });

        jBtnGravar.setText("Gravar");
        jBtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGravarActionPerformed(evt);
            }
        });

        jBtnProximo.setText("Proximo >>");
        jBtnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProximoActionPerformed(evt);
            }
        });

        jBtnAnterior.setText("<< Anterior");
        jBtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnteriorActionPerformed(evt);
            }
        });

        jBtnEditar.setText("Editar");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnRemover.setText("Remover");
        jBtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoverActionPerformed(evt);
            }
        });

        jBtnAbrirArquivo.setText("Abrir Arquivo");
        jBtnAbrirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAbrirArquivoActionPerformed(evt);
            }
        });

        jBtnNovoArquivo.setText("Novo Arquivo");
        jBtnNovoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoArquivoActionPerformed(evt);
            }
        });

        jLabel4.setText("Posição");

        jTFPosicaoAtual.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnGravar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnFechar))
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFPosicaoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTFFone, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtnAnterior))
                                    .addComponent(jSIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtnProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jBtnAbrirArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnNovoArquivo)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNovoArquivo)
                    .addComponent(jBtnAbrirArquivo))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFPosicaoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnProximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnAnterior)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNovo)
                    .addComponent(jBtnGravar)
                    .addComponent(jBtnFechar)
                    .addComponent(jBtnEditar)
                    .addComponent(jBtnRemover))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(446, 285));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoActionPerformed
        limparTela();
        controlaBotoesECampos(false, true, false, false, true);
    }//GEN-LAST:event_jBtnNovoActionPerformed

    private void jBtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFecharActionPerformed
        if (mt != null) {
            mt.fecharArquivo();
        }
        System.exit(0);
    }//GEN-LAST:event_jBtnFecharActionPerformed

    private void jBtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGravarActionPerformed
        if (jTFNome.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o Nome!", "Erro!", JOptionPane.ERROR_MESSAGE); 
           jTFNome.requestFocus();
        } else
        if (jTFFone.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o Fone!", "Erro!", JOptionPane.ERROR_MESSAGE);
           jTFFone.requestFocus();
        } else {
            Cliente cliente = new Cliente(jTFNome.getText(), jTFFone.getText(),
            (Integer)jSIdade.getValue());
            
            boolean sucessoInluirOuAlterarLista = false;

            if (!alterar){
                sucessoInluirOuAlterarLista = listaDeClientes.inserir(cliente);
            } else {
                sucessoInluirOuAlterarLista = listaDeClientes.alterar(cliente, posicaoAtual);   
                alterar = false;
            }   

            if (sucessoInluirOuAlterarLista){
                if (mt.salvaArquivo(listaDeClientes.getLista())){
                    jTFPosicaoAtual.setText(Integer.toString(listaDeClientes.posicaoNaLista(cliente)));
                    JOptionPane.showMessageDialog(null, "Cliente " +cliente.getNome()+ " gravado!", "Gravar", JOptionPane.INFORMATION_MESSAGE);
                } else{
                    JOptionPane.showMessageDialog(null, "Erro ao gravar "+cliente.getNome()+"!", "Erro!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                 JOptionPane.showMessageDialog(null, "Erro ao incluir cliente na lista!", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
            controlaBotoesECampos(true, false, true, true, false);
        }
    }//GEN-LAST:event_jBtnGravarActionPerformed

    private void jBtnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProximoActionPerformed
        Cliente cliente = new Cliente(jTFNome.getText(), "", 0);
        cliente = listaDeClientes.proximo(cliente);
        
        if (cliente != null){
            atualizaCampos(cliente);
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível exibir próximo cliente!","Erro!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtnProximoActionPerformed

    private void jBtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnteriorActionPerformed
        Cliente cliente = new Cliente(jTFNome.getText(), "", 0);
        
        cliente = listaDeClientes.anterior(cliente);
        
        if (cliente != null){
            atualizaCampos(cliente);
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível exibir cliente anterior!","Erro!", JOptionPane.WARNING_MESSAGE);
        } 
        
    }//GEN-LAST:event_jBtnAnteriorActionPerformed

    private void jBtnAbrirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAbrirArquivoActionPerformed
        List<Cliente> lista = new ArrayList<Cliente>();
        
        lista = mt.abrirArquivo();
        
        if (lista != null){
            listaDeClientes.setLista(lista);
            atualizaCampos(listaDeClientes.primeiro());
        } else {
             JOptionPane.showMessageDialog(null, "Sem cadastros!", "Erro Arquivo", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_jBtnAbrirArquivoActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        controlaBotoesECampos(false, true, false, false, true);
        alterar = true;
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoverActionPerformed
        controlaBotoesECampos(true, false, true, true, false);
        
        Cliente cliente = new Cliente(jTFNome.getText(),"", 0);
        
        int resp = JOptionPane.showConfirmDialog(null, "Confirma exlusão?", "Excluir", JOptionPane.YES_NO_OPTION);
        
        if (resp == 0){
            if (listaDeClientes.excluir(cliente)){
                atualizaCampos(listaDeClientes.primeiro());

                if (mt.salvaArquivo(listaDeClientes.getLista())){
                    JOptionPane.showMessageDialog(null, "Cliente " +cliente.getNome()+ " excluído!", "Excluir!", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Não foi possível localizar arquivo ou criar!", "Erro Arquivo", JOptionPane.ERROR_MESSAGE);
                }
            } 
        }
    }//GEN-LAST:event_jBtnRemoverActionPerformed

    private void jBtnNovoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoArquivoActionPerformed
        if (!mt.criarArquivo()){
           JOptionPane.showMessageDialog(null, "Não foi possível localizar arquivo ou criar!", "Erro Arquivo", JOptionPane.ERROR_MESSAGE);
        } else {
            controlaBotoesECampos(true, false, false, false, false);
        }
    }//GEN-LAST:event_jBtnNovoArquivoActionPerformed

    public void limparTela() {
        jTFPosicaoAtual.setText("");
        jTFNome.setText("");
        jTFFone.setText("");
        jSIdade.setValue((Integer) 18);
    }

    public void atualizaCampos(Cliente cliente){        
        if (cliente == null){
            limparTela();
            controlaBotoesECampos(true, false, false, false, false);
        } else {
            posicaoAtual = listaDeClientes.posicaoNaLista(cliente);
            jTFPosicaoAtual.setText(Integer.toString(posicaoAtual));
            jTFNome.setText(cliente.getNome());
            jTFFone.setText(cliente.getFone());
            jSIdade.setValue(cliente.getIdade());
            controlaBotoesECampos(true, false, true, true, false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JanelaCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAbrirArquivo;
    private javax.swing.JButton jBtnAnterior;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnFechar;
    private javax.swing.JButton jBtnGravar;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnNovoArquivo;
    private javax.swing.JButton jBtnProximo;
    private javax.swing.JButton jBtnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jSIdade;
    private javax.swing.JTextField jTFFone;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPosicaoAtual;
    // End of variables declaration//GEN-END:variables
}
